# Site settings | 网站设置
title: happy1slm
SEOTitle: happy1slm的博客 | happy1slm
header-img: img/HomePage04.jpg
email: 252765504@qq.com
wechat: happy1slm
description: "happy1slm的博客"
keyword: "happy1slm, happy1slm的博客, "
url: "http://happy1slm.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/happy1slm/happy1slm.github.io.git" #code repository | 代码仓库





# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "读书|健身|投资|帮朋友|陪家人"
sidebar-avatar: /img/Andy01.jpg      # 头像





# SNS settings | 社交网络设置
github_username: happy1slm




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 45e38d020b8126a30379                            #生成的clientID
  clientSecret: 8f56467ce6c923ee693ca23ce75bddba3a564bbe    #生成的clientSecret
  repo: happy1slm.github.io    #仓库名称
  owner: happy1slm    # github用户名
  admin: happy1slm
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 14495afb594a7ffbd875c06118605a32
# 原始ID:9acee03023ad0c6c993dd86df81e2ac8


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·happy1slm",
        href: "http://happy1slm.com"
    }
]

theme: jekyll-theme-merlot
